# Generated by Django 3.0.4 on 2020-03-04 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_pub', models.DateTimeField(auto_now=True, verbose_name='Data de Publicação')),
                ('data_edi', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atualização')),
                ('autor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
